@:
	@echo "No build instructions. Only install and remove"

install:
	install -Dm 755 the_blizzard.sh /usr/local/bin/the_blizzard.sh
	install -Dm 644 the_blizzard.cron /etc/cron.d/the_blizzard

remove:
	rm /usr/local/bin/the_blizzard.sh
	rm /etc/cron.d/the_blizzard
